---
version: "3.5"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    networks:
      - grafana
      - proxy
    volumes:
    - /home/leshevi/grafana/grafana:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=u
      - GF_SECURITY_ADMIN_PASSWORD=u
      - GF_INSTALL_PLUGINS= #grafana-worldmap-panel
#    links:
#      - influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.iii.ru`)"
      #- "traefik.http.routers.grafana.middlewares=default-ipAllowList@file"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.iii.ru`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=homelab
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=home
    networks:
      - grafana
    volumes:
      - /home/leshevi/grafana/influxdb:/var/lib/influxdb2
    ports:
     - 8086:8086
     - 8089:8089/udp
  telegraf:
    container_name: telegraf
    image: telegraf
    restart: unless-stopped
    user: telegraf:997 #you need to find the GID of Docker if not added to Sudo group
    #entrypoint: /bin/bash -c "chmod 777 /var/run/docker.sock && /entrypoint.sh telegraf"
    networks:
      - grafana
    volumes:
      - /home/leshevi/grafana/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro # to monitor docker-vm
      - /var/run/docker.sock:/var/run/docker.sock # to monitor docker containers
      #- '/home/stilicho/docker/grafana/telegraf/mibs:/usr/share/snmp/mibs' # mibs files
    ports:
      - 8125:8125
    depends_on:
      - influxdb
 #   links:
 #     - influxdb
    environment:
        - HOST_ETC=/hostfs/etc
        - HOST_PROC=/hostfs/proc
        - HOST_SYS=/hostfs/sys
        - HOST_VAR=/hostfs/var
        - HOST_RUN=/hostfs/run
        - HOST_MOUNT_PREFIX=/hostfs 
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9092:9090
    volumes:
      - /home/leshevi/grafana/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - grafana
      - proxy

networks:
  grafana:
  proxy:
    external: true
