services:
  notebook:
    build:
     context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./app:/app
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notebook.entrypoints=http"
      - "traefik.http.routers.notebook.rule=Host(`domain`)"
      - "traefik.http.middlewares.notebook-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.notebook.middlewares=notebook-https-redirect"
      - "traefik.http.routers.notebook-secure.entrypoints=https"
      - "traefik.http.routers.notebook-secure.rule=Host(`domain`)"
      - "traefik.http.routers.notebook-secure.tls=true"
      - "traefik.http.routers.notebook-secure.service=notebook"
      - "traefik.http.services.notebook.loadbalancer.server.port=8888"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
